# Generated by Django 4.0.3 on 2023-05-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.FloatField(),
        ),
    ]
